use capstone;
rename table `orders 1` to orders1;

-- task3
-- Join orders, order_items, and products to display detailed line items.
select ord.order_id,ord.customer_id,ord.store_id,p.product_name,p.product_id,p.category_id,od.item_id,od.list_price
from capstone.orders1 as ord
inner join capstone.order_items1 as od
on ord.order_id=od.order_id
inner join capstone.product_id1 as p
on od.product_id=p.product_id;

-- task4
-- Write a query to group sales (total_price) by each store_id.
select ord.store_id,sum(od.quantity*od.list_price*(1-od.discount))
from capstone.orders1 as ord
inner join capstone.order_items1 as od
on ord.order_id=od.order_id group by ord.store_id;

-- task5
-- Use ORDER BY and LIMIT to get the top 5 most sold products byquantity.
select p.product_name,od.order_id,od.quantity
from capstone.product_id1 as p
inner join capstone.order_items1 as od
on p.product_id=od.product_id  group by p.product_name,od.order_id,od.quantity order by quantity desc limit 5;

-- task 6
-- For each customer, return total orders placed, total items purchased,and total revenue.
select ord.order_id,od.item_id,sum(od.quantity*od.list_price*(1-od.discount)) as revenue,cus.first_name
from capstone.orders1 as ord
inner join capstone.order_items1 as od
on ord.order_id=od.order_id
inner join capstone.customers as cus
on ord.customer_id=cus.customer_id group by ord.order_id,od.item_id,cus.first_name;

-- task7
-- Write a query to classify customers into spending brackets (e.g., low,medium, high).
select cus.first_name,sum(od.quantity*od.list_price*(1-od.discount)) as total_spending ,
case when sum(od.quantity*od.list_price*(1-od.discount)) > 2000 then "high" when sum(od.quantity*od.list_price*(1-od.discount)) > 1000 then "medium" when sum(od.quantity*od.list_price*(1-od.discount))<500 then "low" else "NA"
end as total_spending from capstone.customers as cus inner join capstone.orders1 as ord on cus.customer_id=ord.customer_id inner join capstone.order_items1 as od on od.order_id=ord.order_id group by cus.first_name order by total_spending desc;

-- task8
-- Analyze total revenue generated by each staff member based on their handled orders.
Select ord.staff_id,ord.order_id,s.first_name,SUM(od.quantity * od.list_price * (1 - od.discount)) AS revenue
from capstone.orders1 AS ord
inner join capstone.staff1 AS s 
on  s.staff_id = ord.staff_id
inner join capstone.order_items1 AS od 
on od.order_id = ord.order_id group by ord.staff_id , order_id , s.first_name order by revenue desc;

-- task9
-- Write a query to list products where stock quantity < 10 in any store.
select s.product_id,s.quantity,sto.store_name from capstone.stockl1 as s
inner join capstone.stores1 as sto on s.store_id=sto.store_id where s.quantity <10 group by s.product_id,s.quantity,sto.store_name;

-- task10
-- Create a table customer_segments that will be populated from Python ML results later.


